spring.application.name=backend

server.port=8081

# ==============================================================
# CONFIGURACION DE POSTGRESQL
# ==============================================================
# Reemplaza 'bodega_db' por el nombre de tu base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/vehiculos_bd
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================================================
# CONFIGURACION DE JPA / HIBERNATE
# ==============================================================
# 'update' crea las tablas automaticamente segun tus @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==============================================================
# CONFIGURACION DE DEVTOOLS
# ==============================================================
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# ==============================================================
# CONFIGURACION DE SWAGGER
# ==============================================================
# Ruta personalizada para la interfaz de Swagger
springdoc.swagger-ui.path=/swagger-ui.html
# Ruta para el JSON de la especificación OpenAPI
springdoc.api-docs.path=/api-docs